config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments, :likes
  end
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, constraints: { id: /[0-9]+/ } do
    resources :follows
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, foreign_key: 'post_id'
  belongs_to :user, foreign_key: 'user_id'
end

app/models/follow.rb
class Follow < ApplicationRecord
  has_many :users
  belongs_to :user, foreign_key: 'user_id'
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
    belongs_to :post, foreign_key: 'post_id'
    has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many_attached :images
  has_many :comments
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followers, class_name: 'Follow', foreign_key: 'follower_id'
  has_many :followings, class_name: 'Follow', foreign_key: 'following_id'
  has_many :posts
  has_many :comments
  has_many :like, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[create destroy]
  before_action :set_comment, only: %i[destroy]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_path(@post), notice: "Comment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy

    redirect_to post_path(@post), notice: "Comment was successfully destroyed."
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @follow = Follow.new(follow_params)
    @follow.user_id = current_user.id
    return unless @follow.save

    redirect_to user_path(@follow.request_by_id)
  end

  def update
    @follow_for_following = Follow.find(params[:id])
    @follow_for_following.following_id = @follow_for_following.request_to_id
   
    @follow_for_followers = Follow.create(follower_id: @follow_for_following.request_by_id, user_id: params[:user_id])
    @follow_for_following.save
    debugger
    redirect_to user_path(current_user.id)
  end

  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy
    redirect_to users_path
  end

  private

  def follow_params
    params.require(:follow).permit(:request_to_id, :request_by_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
    @posts = Post.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  def create
    @comment = Comment.new
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      @comment.post_id = @post.id
      redirect_to root_path(@post)
    else
      render ''
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, images: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @follow = Follow.new
  end

  def show
    @posts = Post.where(user_id: current_user.id)
    @user = User.find(current_user.id)
    @request_bys = Follow.where(user_id: current_user.id)
    @request_tos = Follow.where(request_to_id: current_user.id)
  end

  private

  def follow_params
    params.require(:follow).permit(:request_to_id, :request_by_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render "/layouts/navbar" %>
<% @posts.each do |post|%>
    
    <p><%= post.title%></p>
    <p>
    <a href = "<%= post_path(post.id)%>">
    <% post.images.attach(params[:images]).map do |image| %>
       <%= image_tag image.representation(resize_to_limit: [300, 300])%>
    <%end%>
     </a>
    </p>
    <p><%= post.content%></p>
    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <h6>Comments</h6>
    <% post.comments.map do |comment|%>
    <%= comment.body%><br>
    <%end%>
   <hr>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <span role="button"  aria-expanded="false" class ="nav-link"><%=link_to "Home", root_path%></span>
      </li>
      <li class="nav-item">
        <span class="nav-link "  role="button"  aria-expanded="false"><%= link_to "Users", users_path%> </span>
      </li>
      <li class="nav-item dropdown">
       <%if current_user != nil%>
        <a class="nav-link" href = "<%= user_path(current_user.id)%>">
         <img class="rounded-circle shadow-4-strong" width="50" height="50" alt="avatar2" src="https://mdbcdn.b-cdn.net/img/new/avatars/1.webp"/>
        </a>
        <%end%>
      </li>
      <li class="nav-item">
          <span class="nav-link "  role="button"  aria-expanded="false">
           <% if user_signed_in? %> 
             <%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: "delete" } %>
            <% else %>
             <%= link_to "Sign in", new_user_session_path, method: :get %>
           <% end %>
          </span>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMediaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
     <!-- <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p> --> 

    <%= yield %>
  </body>
</html>

app/views/posts/_comment_form.html.erb
<%= form_with(model: [post, post.comments.build]) do |form| %>
  <div class="mb-3">
    <%= form.label :body, "Comment message", class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/_post_form.html.erb
<h2>Insert a post from here</h2>
<%= form_with model: @post, url: "/posts" do |f| %>
    <%= f.label :title, "Title:"%>
    <%= f.text_field :title, placeholder: 'Enter article title here' %><br><br>
     <%= f.label :images, "Select a Image:"%>
    <%= f.file_field :images, :multiple => true %><br><br>
     <%= f.label :content, "Content"%>
    <%= f.text_area :content, placeholder: "Enter article content here"%><br>
    <%= f.submit "post" %>
<% end %>

app/views/posts/show.html.erb
<%= render "/layouts/navbar" %>
    <p><%= @post.title%></p>
    <p>
    <% @post.images.attach(params[:images]).map do |image| %>
       <%= image_tag image.representation(resize_to_limit: [600, 600])%>
    <%end%>
    </p>
    <p><%= @post.content%></p>
    <%if current_user.present?%>
    <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
    <% if pre_like %>
      <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
    <% else %>
      <%= button_to 'Like', post_likes_path(@post), method: :post %>
    <% end %>
    <%else%>
    <%= %>
    <%end%>
<h6>Comments</h6>
<hr>
<% if @comments.any? %>
  <% @comments.each do |comment| %>
    <div>
      <p><%= comment.body %></p>
      <%if current_user != nil%>
        <% if comment.user_id == current_user.id || @post.user_id == current_user.id %>
          <%= button_to "Destroy this comment", post_comment_path(@post, comment), method: :delete, class: "btn btn-danger", form: { data: { turbo_confirm: "Are you sure?" } } %>
        <%end%>
      <%end%>
    </div>
  <% end %>
<% else %>
  <p>No comments found.</p>
<% end %>

<%if current_user != nil%>
  <h5>Add a new comment</h5>
  <%= render partial: "posts/comment_form", locals: { post: @post } %>
<%else%>
    <p>Please login to comment this post</p>
<%end%>

app/views/users/index.html.erb
<%= render "/layouts/navbar" %>
<h1>All users of this social sites</h1>
<%if current_user==nil%>
    <p>Please Sign in to see the users of this applications</p>
<%else%>
<% @users.each do |user|%>
    <%if user != current_user%>
        <%= user.user_name%>
        <%pre_send_request = Follow.where(request_by_id: current_user.id, request_to_id: user.id)%> 
        <%if pre_send_request == []%>
            <%= form_with model: @follow, url: user_follows_path(user), method: "POST" do |form| %>
                <%= form.hidden_field :request_by_id, value: current_user.id %>
                <%= form.hidden_field :request_to_id, value: user.id %>
                <%= form.submit "send follow request"%><br>
            <% end %>   
        <%else%>
            <%if pre_send_request.any?%>
            <%= button_to "undo request", user_follow_path(user.id, pre_send_request.ids), method: :delete, form: {data: {turbo_confirm: "Are you sure?"}} %><br>
            <%end%>
        <%end%>

    <%end%>
<%end%>
<%end%>

app/views/users/show.html.erb
<%= render "/layouts/navbar" %>
<%= render "/posts/post_form"%>
<h1> Your profile detail: </h1>
<p>UserName: <%= current_user.user_name%></p>
<p>Email: <%= current_user.email%></p>
<%if @posts.any?%>
<h2>The post you have created are:</h2>
<% @posts.each do |post|%>
    
    <p><%= post.title%></p>
    <p>
    <a href = "<%= post_path(post.id)%>">
    <% post.images.attach(params[:images]).map do |image| %>
       <%= image_tag image.representation(resize_to_limit: [300, 300])%>
    <%end%>
     </a>
    </p>
    <p><%= post.content%></p>
    <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <h6>Comments</h6>
    <% post.comments.map do |comment|%>
    <%= comment.body%><br>
    <%end%>
   <hr>
<%end%>
<%end%>
<h2>Notifications</h2>
<% @request_bys.each do |follow|%>
<% if follow.request_to_id%>
<p> You have successfully send the friend request to: <%=User.find(follow.request_to_id).user_name %></p>
<%= button_to 'Undo', user_follow_path(User.find(follow.request_to_id).id, follow.id), method: :delete, form: {data: {turbo_confirm: "Are you sure?"}} %>
<%end%>
<%end%>
<hr>
<%@request_tos.each do |follow|%>
<% if follow.request_by_id !=current_user.id%>
<p>  friend request has been sent by: <%=User.find(follow.request_by_id).user_name %></p>
<%debugger%>
<%if current_user.followers.include?(follow.follower_id)%>
<%= button_to 'Accept', user_follow_path(current_user.id , follow), method: :put%>
<%= button_to 'Reject',user_follow_path(User.find(follow.request_by_id).id, follow.id), method: :delete,form: {data: {turbo_confirm: "Are you sure?", disable_with: 'loading..'}} %>
<%end%>
<%end%>
<%end%>  